service: sls-*NAME*-api
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: me-south-1
  stage: prod
  apiGateway:
    binaryMediaTypes:
      - multipart/form-data
  deploymentMethod: direct
functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: /
          method: post
          cors:
            origin: true
      - http:
          path: /
          method: options
          cors:
            origin: true
  redirect:
    handler: src/redirect.redirectHandler
    events:
      - http:
          path: /
          method: get
          cors:
            origin: true
  cronExpireTokens:
    handler: src/cron-jobs.expireTokens
    events:
      - schedule: rate(1 hour)
plugins:
  - serverless-domain-manager
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-api-gateway-throttling
  - serverless-webpack-prisma
custom:
  includeDependencies: true
  webpack:
    includeModules:
      forceInclude:
        - prisma
    packager: 'yarn'
    packagerOptions:
      scripts:
        - npx prisma generate
  customDomain:
    domainName: *API_URL*
    basePath: ''
    createRoute53Record: true
    stage: ${self:provider.stage}
  apiGatewayThrottling:
    maxRequestsPerSecond: 2000
    maxConcurrentRequests: 500
package:
  patterns:
    - '!src/graphql.ts'
